name = "hevy-planner"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[assets]
directory = "public"

[[d1_databases]]
binding = "DB"
database_name = "hevy-planner"
database_id = "856703c5-ee18-43c5-b910-4ee8f27742f4"

[vars]
ENVIRONMENT = "development"

# Production deploy: wrangler deploy --env production
[env.production]
[env.production.vars]
ENVIRONMENT = "production"
